name: Your Name
title: "Your Name — Portfolio"
description: "Personal portfolio showcasing projects, skills, and contact information."
url: ""
baseurl: ""
markdown: kramdown
kramdown:
  input: GFM
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - package.json
  - package-lock.json
defaults:
  - scope:
      path: ""
    values:
      layout: default
permalink: pretty